// import { SERVICE_MSG } from './response';

export const SERVICE_MSG={
    ISEXIST:'WITH THIS CATEGORY_ID,THE SERVICE ALREADY EXIST',
    CREATED:'SERVICE SUCCESSFULLY ADDED IN THE DATABASE',
    NOTCREATED:'SERVICE NOT CREATED'
}
export const SERVICE_MSG_CODE={
    ISEXIST:1
}

export const RESPONSE_CODES = {
    CREATED: 201,
    SUCCESS: 200,
    BADREQUEST: 400,
    UNAUTHORIZED:401,
    NOTFOUND:404,
    CONFLICT: 409,
    INTERNAL_SERVER_ERROR: 500,
    
};